### ISSUE TITLE
rajouter fonction reseaux

### ISSUE THREAD

**Issue by bkoj-arch** [bkoj-arch/testgit#1]
faire le client python socket et le serveur
Commencer a rajouter le prtocol FTP

**Comment by M-D-Q** [comment]
fait

**Comment by bkoj-arch** [comment]
regarde plutot ca: https://wiki.archlinux.org/title/ProFTPD

et pour les sockets peut etre regarde la doc officielle

**Comment by bkoj-arch** [comment]
depeche aussi stp
